# Laravel Forge Deployment Script for HB837 Training Server
# Author: Generated by Task 7
# Date: July 15, 2025

param(
    [Parameter(Mandatory=$false)]
    [string]$ForgeServer = "projecttracker.hb837training.com",
    
    [Parameter(Mandatory=$false)]
    [string]$ProjectPath = "/home/projecttracker/projecttracker.hb837training.com",
    
    [Parameter(Mandatory=$false)]
    [string]$ForgeUser = "projecttracker",
    
    [switch]$UpdateDatabase,
    [switch]$RunMigrations,
    [switch]$RunSeeders,
    [switch]$Force,
    [switch]$DryRun,
    [switch]$BackupOnly
)

# HB837 Training Server Configuration
# Server ID: 783941
# Site ID: 2763978
# Public IP: 54.158.31.216
# Private IP: 10.0.1.86
# Region: Virginia (Ubuntu 22.04)

Write-Host "🚀 Laravel Forge Deployment Script - HB837 Training Server" -ForegroundColor Green
Write-Host "=================================================" -ForegroundColor Green

# Load configuration
$configPath = "$PSScriptRoot\deploy-config.json"
if (Test-Path $configPath) {
    $config = Get-Content $configPath | ConvertFrom-Json
    Write-Host "✅ Configuration loaded from deploy-config.json" -ForegroundColor Green
} else {
    Write-Host "⚠️  Configuration file not found, using default values" -ForegroundColor Yellow
}

# Display deployment information
Write-Host "`n📊 Deployment Information:" -ForegroundColor Cyan
Write-Host "   Server: $ForgeServer" -ForegroundColor White
Write-Host "   User: $ForgeUser" -ForegroundColor White
Write-Host "   Path: $ProjectPath" -ForegroundColor White
Write-Host "   Update Database: $UpdateDatabase" -ForegroundColor White
Write-Host "   Run Migrations: $RunMigrations" -ForegroundColor White
Write-Host "   Dry Run: $DryRun" -ForegroundColor White

# Safety confirmation unless Force is used
if (-not $Force -and -not $DryRun) {
    Write-Host "`n⚠️  WARNING: This will replace production folders!" -ForegroundColor Red
    Write-Host "   Folders to replace: app, config, database, resources, routes" -ForegroundColor Yellow
    $confirmation = Read-Host "   Continue with deployment? (y/N)"
    if ($confirmation -ne 'y' -and $confirmation -ne 'Y') {
        Write-Host "❌ Deployment cancelled by user" -ForegroundColor Red
        exit 1
    }
}

# Function to execute SSH commands
function Invoke-SSHCommand {
    param([string]$Command, [string]$Description)
    
    Write-Host "   🔄 $Description..." -ForegroundColor Yellow
    
    if ($DryRun) {
        Write-Host "      [DRY RUN] Would execute: ssh $ForgeUser@$ForgeServer '$Command'" -ForegroundColor Magenta
        return $true
    }
    
    try {
        $result = ssh "$ForgeUser@$ForgeServer" "$Command" 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Host "      ✅ $Description completed" -ForegroundColor Green
            return $true
        } else {
            Write-Host "      ❌ Error: $result" -ForegroundColor Red
            return $false
        }
    }
    catch {
        Write-Host "      ❌ Error: $($_.Exception.Message)" -ForegroundColor Red
        return $false
    }
}

# Main deployment process
Write-Host "`n🔧 Starting Deployment Process..." -ForegroundColor Cyan

# Step 1: Test SSH connection
Write-Host "`n1️⃣ Testing SSH Connection..." -ForegroundColor Cyan
if (-not (Invoke-SSHCommand "echo 'Connection test successful'" "Testing SSH connection")) {
    Write-Host "❌ SSH connection failed. Please check your SSH configuration." -ForegroundColor Red
    exit 1
}

# Step 2: Create backup
Write-Host "`n2️⃣ Creating Backup..." -ForegroundColor Cyan
$timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
$backupPath = "/home/$ForgeUser/backups/deployment_$timestamp"

if (-not (Invoke-SSHCommand "mkdir -p $backupPath" "Creating backup directory")) {
    Write-Host "❌ Failed to create backup directory" -ForegroundColor Red
    exit 1
}

# Backup existing folders
$foldersToBackup = @("app", "config", "database", "resources", "routes")
foreach ($folder in $foldersToBackup) {
    $backupCommand = "if [ -d '$ProjectPath/$folder' ]; then cp -r '$ProjectPath/$folder' '$backupPath/'; else echo 'Folder $folder not found, skipping backup'; fi"
    Invoke-SSHCommand $backupCommand "Backing up $folder"
}

if ($BackupOnly) {
    Write-Host "`n✅ Backup completed successfully at: $backupPath" -ForegroundColor Green
    Write-Host "   Backup location: $ForgeUser@$ForgeServer`:$backupPath" -ForegroundColor White
    exit 0
}

# Step 3: Remove existing folders
Write-Host "`n3️⃣ Removing Existing Folders..." -ForegroundColor Cyan
foreach ($folder in $foldersToBackup) {
    Invoke-SSHCommand "rm -rf $ProjectPath/$folder" "Removing $folder"
}

# Step 4: Copy new folders (simplified for Windows)
Write-Host "`n4️⃣ Copying New Folders..." -ForegroundColor Cyan
$currentDir = Get-Location
foreach ($folder in $foldersToBackup) {
    $localPath = "$currentDir\$folder"
    if (Test-Path $localPath) {
        Write-Host "   📁 Copying $folder..." -ForegroundColor Yellow
        if ($DryRun) {
            Write-Host "      [DRY RUN] Would copy: $localPath -> $ForgeUser@$ForgeServer`:$ProjectPath/" -ForegroundColor Magenta
        } else {
            try {
                & scp -r "$localPath" "$ForgeUser@$ForgeServer`:$ProjectPath/"
                Write-Host "      ✅ Copying $folder completed" -ForegroundColor Green
            }
            catch {
                Write-Host "      ❌ Error copying $folder`: $($_.Exception.Message)" -ForegroundColor Red
            }
        }
    } else {
        Write-Host "   ⚠️  Local folder '$folder' not found, skipping" -ForegroundColor Yellow
    }
}

# Step 5: Run Laravel optimizations
Write-Host "`n5️⃣ Running Laravel Optimizations..." -ForegroundColor Cyan

# Change to project directory and run commands
$cdCommand = "cd $ProjectPath"

# Composer dump-autoload
Invoke-SSHCommand "$cdCommand; composer dump-autoload --optimize" "Running composer dump-autoload"

# Laravel optimize clear
Invoke-SSHCommand "$cdCommand; php artisan optimize:clear" "Running php artisan optimize:clear"

# Optional additional optimizations
Invoke-SSHCommand "$cdCommand; php artisan config:cache" "Caching configuration"
Invoke-SSHCommand "$cdCommand; php artisan route:cache" "Caching routes"
Invoke-SSHCommand "$cdCommand; php artisan view:cache" "Caching views"

# Step 6: Database operations (if requested)
if ($UpdateDatabase -or $RunMigrations -or $RunSeeders) {
    Write-Host "`n6️⃣ Database Operations..." -ForegroundColor Cyan
    
    # Create database backup (simplified)
    Write-Host "   💾 Creating database backup..." -ForegroundColor Yellow
    $dbBackupFile = "database_backup_$timestamp.sql"
    Invoke-SSHCommand "$cdCommand; mysqldump --single-transaction \$DB_DATABASE > $backupPath/$dbBackupFile" "Creating database backup"
    
    if ($RunMigrations) {
        if (-not (Invoke-SSHCommand "$cdCommand; php artisan migrate --force" "Running database migrations")) {
            Write-Host "❌ Database migrations failed!" -ForegroundColor Red
            Write-Host "   Consider running rollback: ssh $ForgeUser@$ForgeServer" -ForegroundColor Yellow
        }
    }
    
    if ($RunSeeders) {
        Invoke-SSHCommand "$cdCommand; php artisan db:seed --force" "Running database seeders"
    }
}

# Step 7: Final verification
Write-Host "`n7️⃣ Final Verification..." -ForegroundColor Cyan
Invoke-SSHCommand "$cdCommand; php artisan --version" "Verifying Laravel installation"

# Completion message
Write-Host "`n🎉 Deployment Completed Successfully!" -ForegroundColor Green
Write-Host "=================================================" -ForegroundColor Green
Write-Host "   Server: $ForgeServer" -ForegroundColor White
Write-Host "   Backup Location: $backupPath" -ForegroundColor White
Write-Host "   Timestamp: $timestamp" -ForegroundColor White

if (-not $DryRun) {
    Write-Host "`n📋 Next Steps:" -ForegroundColor Cyan
    Write-Host "   1. Test the application: https://$ForgeServer" -ForegroundColor White
    Write-Host "   2. Monitor logs for any issues" -ForegroundColor White
    Write-Host "   3. Backup location: $ForgeUser@$ForgeServer`:$backupPath" -ForegroundColor White
}

Write-Host "`n✅ Deployment script completed!" -ForegroundColor Green
