#!/bin/bash
# Laravel Forge Deployment Script for HB837 Training Server
# Author: Generated by Task 7
# Date: July 15, 2025

# HB837 Training Server Configuration
FORGE_SERVER="projecttracker.hb837training.com"
PROJECT_PATH="/home/projecttracker/projecttracker.hb837training.com"
FORGE_USER="projecttracker"
SERVER_ID="783941"
SITE_ID="2763978"
PUBLIC_IP="54.158.31.216"
PRIVATE_IP="10.0.1.86"

# Deployment Configuration
UPDATE_DB=false
RUN_MIGRATIONS=false
RUN_SEEDERS=false
FORCE=false
DRY_RUN=false
BACKUP_ONLY=false

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_info() {
    echo -e "${CYAN}📊 $1${NC}"
}

print_progress() {
    echo -e "${YELLOW}🔄 $1${NC}"
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --server)
            FORGE_SERVER="$2"
            shift 2
            ;;
        --path)
            PROJECT_PATH="$2"
            shift 2
            ;;
        --user)
            FORGE_USER="$2"
            shift 2
            ;;
        --update-db)
            UPDATE_DB=true
            shift
            ;;
        --migrations)
            RUN_MIGRATIONS=true
            shift
            ;;
        --seeders)
            RUN_SEEDERS=true
            shift
            ;;
        --force)
            FORCE=true
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --backup-only)
            BACKUP_ONLY=true
            shift
            ;;
        --help)
            echo "Laravel Forge Deployment Script for HB837"
            echo ""
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --server SERVER    Forge server hostname (default: $FORGE_SERVER)"
            echo "  --path PATH        Project path on server (default: $PROJECT_PATH)"
            echo "  --user USER        SSH user (default: $FORGE_USER)"
            echo "  --update-db        Update database"
            echo "  --migrations       Run database migrations"
            echo "  --seeders          Run database seeders"
            echo "  --force            Skip confirmation prompts"
            echo "  --dry-run          Show what would be done without executing"
            echo "  --backup-only      Create backup only, skip deployment"
            echo "  --help             Show this help message"
            echo ""
            echo "Examples:"
            echo "  $0                                    # Basic deployment"
            echo "  $0 --update-db --migrations           # Deploy with database updates"
            echo "  $0 --dry-run                          # See what would be done"
            echo "  $0 --backup-only                      # Create backup only"
            exit 0
            ;;
        *)
            print_error "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Header
echo -e "${GREEN}🚀 Laravel Forge Deployment Script - HB837 Training Server${NC}"
echo -e "${GREEN}=================================================${NC}"

# Display deployment information
print_info "Deployment Information:"
echo "   Server: $FORGE_SERVER"
echo "   User: $FORGE_USER"
echo "   Path: $PROJECT_PATH"
echo "   Update Database: $UPDATE_DB"
echo "   Run Migrations: $RUN_MIGRATIONS"
echo "   Dry Run: $DRY_RUN"

# Safety confirmation unless Force is used
if [[ "$FORCE" != "true" && "$DRY_RUN" != "true" ]]; then
    echo ""
    print_warning "WARNING: This will replace production folders!"
    echo "   Folders to replace: app, config, database, resources, routes"
    read -p "   Continue with deployment? (y/N): " confirmation
    if [[ "$confirmation" != "y" && "$confirmation" != "Y" ]]; then
        print_error "Deployment cancelled by user"
        exit 1
    fi
fi

# Function to execute SSH commands
execute_ssh_command() {
    local command="$1"
    local description="$2"
    
    print_progress "$description..."
    
    if [[ "$DRY_RUN" == "true" ]]; then
        echo -e "      ${MAGENTA}[DRY RUN] Would execute: ssh $FORGE_USER@$FORGE_SERVER '$command'${NC}"
        return 0
    fi
    
    if ssh "$FORGE_USER@$FORGE_SERVER" "$command"; then
        echo -e "      ${GREEN}✅ $description completed${NC}"
        return 0
    else
        echo -e "      ${RED}❌ Error: $description failed${NC}"
        return 1
    fi
}

# Function to copy folders via SCP
copy_folder_to_forge() {
    local local_folder="$1"
    local remote_folder="$2"
    local description="$3"
    
    print_progress "$description..."
    
    if [[ "$DRY_RUN" == "true" ]]; then
        echo -e "      ${MAGENTA}[DRY RUN] Would copy: $local_folder -> $FORGE_USER@$FORGE_SERVER:$remote_folder${NC}"
        return 0
    fi
    
    if scp -r "$local_folder" "$FORGE_USER@$FORGE_SERVER:$remote_folder"; then
        echo -e "      ${GREEN}✅ $description completed${NC}"
        return 0
    else
        echo -e "      ${RED}❌ Error copying $local_folder${NC}"
        return 1
    fi
}

# Main deployment process
echo ""
print_info "Starting Deployment Process..."

# Step 1: Test SSH connection
echo ""
echo -e "${CYAN}1️⃣ Testing SSH Connection...${NC}"
if ! execute_ssh_command "echo 'Connection test successful'" "Testing SSH connection"; then
    print_error "SSH connection failed. Please check your SSH configuration."
    exit 1
fi

# Step 2: Create backup
echo ""
echo -e "${CYAN}2️⃣ Creating Backup...${NC}"
timestamp=$(date +"%Y-%m-%d_%H-%M-%S")
backup_path="/home/$FORGE_USER/backups/deployment_$timestamp"

if ! execute_ssh_command "mkdir -p $backup_path" "Creating backup directory"; then
    print_error "Failed to create backup directory"
    exit 1
fi

# Backup existing folders
folders_to_backup=("app" "config" "database" "resources" "routes")
for folder in "${folders_to_backup[@]}"; do
    execute_ssh_command "cp -r $PROJECT_PATH/$folder $backup_path/ 2>/dev/null || echo 'Folder $folder not found, skipping backup'" "Backing up $folder"
done

if [[ "$BACKUP_ONLY" == "true" ]]; then
    echo ""
    print_status "Backup completed successfully at: $backup_path"
    echo "   Backup location: $FORGE_USER@$FORGE_SERVER:$backup_path"
    exit 0
fi

# Step 3: Remove existing folders
echo ""
echo -e "${CYAN}3️⃣ Removing Existing Folders...${NC}"
for folder in "${folders_to_backup[@]}"; do
    execute_ssh_command "rm -rf $PROJECT_PATH/$folder" "Removing $folder"
done

# Step 4: Copy new folders
echo ""
echo -e "${CYAN}4️⃣ Copying New Folders...${NC}"
current_dir=$(pwd)
for folder in "${folders_to_backup[@]}"; do
    local_path="$current_dir/$folder"
    if [[ -d "$local_path" ]]; then
        copy_folder_to_forge "$local_path" "$PROJECT_PATH/" "Copying $folder"
    else
        print_warning "Local folder '$folder' not found, skipping"
    fi
done

# Step 5: Run Laravel optimizations
echo ""
echo -e "${CYAN}5️⃣ Running Laravel Optimizations...${NC}"

# Change to project directory and run commands
cd_command="cd $PROJECT_PATH"

# Composer dump-autoload
if ! execute_ssh_command "$cd_command && composer dump-autoload --optimize" "Running composer dump-autoload"; then
    print_warning "Composer dump-autoload failed, continuing..."
fi

# Laravel optimize clear
if ! execute_ssh_command "$cd_command && php artisan optimize:clear" "Running php artisan optimize:clear"; then
    print_warning "Laravel optimize:clear failed, continuing..."
fi

# Optional additional optimizations (could read from config)
execute_ssh_command "$cd_command && php artisan config:cache" "Caching configuration"
execute_ssh_command "$cd_command && php artisan route:cache" "Caching routes"
execute_ssh_command "$cd_command && php artisan view:cache" "Caching views"

# Step 6: Database operations (if requested)
if [[ "$UPDATE_DB" == "true" || "$RUN_MIGRATIONS" == "true" || "$RUN_SEEDERS" == "true" ]]; then
    echo ""
    echo -e "${CYAN}6️⃣ Database Operations...${NC}"
    
    # Create database backup
    print_progress "Creating database backup..."
    db_backup_file="database_backup_$timestamp.sql"
    execute_ssh_command "$cd_command && php artisan db:backup $backup_path/$db_backup_file 2>/dev/null || mysqldump --single-transaction --routines --triggers \$(php artisan tinker --execute='echo config(\"database.connections.mysql.database\");') > $backup_path/$db_backup_file" "Creating database backup"
    
    if [[ "$RUN_MIGRATIONS" == "true" ]]; then
        if ! execute_ssh_command "$cd_command && php artisan migrate --force" "Running database migrations"; then
            print_error "Database migrations failed!"
            echo "   Consider running rollback: ssh $FORGE_USER@$FORGE_SERVER"
        fi
    fi
    
    if [[ "$RUN_SEEDERS" == "true" ]]; then
        execute_ssh_command "$cd_command && php artisan db:seed --force" "Running database seeders"
    fi
fi

# Step 7: Final verification
echo ""
echo -e "${CYAN}7️⃣ Final Verification...${NC}"
execute_ssh_command "$cd_command && php artisan --version" "Verifying Laravel installation"

# Completion message
echo ""
echo -e "${GREEN}🎉 Deployment Completed Successfully!${NC}"
echo -e "${GREEN}=================================================${NC}"
echo "   Server: $FORGE_SERVER"
echo "   Backup Location: $backup_path"
echo "   Timestamp: $timestamp"

if [[ "$DRY_RUN" != "true" ]]; then
    echo ""
    print_info "Next Steps:"
    echo "   1. Test the application: https://$FORGE_SERVER"
    echo "   2. Monitor logs for any issues"
    echo "   3. Backup location: $FORGE_USER@$FORGE_SERVER:$backup_path"
fi

echo ""
print_status "Deployment script completed!"
