#!/bin/bash
# Laravel Forge Rollback Script for HB837 Training Server
# Author: Generated by Task 7
# Date: July 15, 2025

# HB837 Training Server Configuration
FORGE_SERVER="projecttracker.hb837training.com"
PROJECT_PATH="/home/projecttracker/projecttracker.hb837training.com"
FORGE_USER="projecttracker"
BACKUP_PATH=""
FORCE=false
DRY_RUN=false

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_info() {
    echo -e "${CYAN}📊 $1${NC}"
}

print_progress() {
    echo -e "${YELLOW}🔄 $1${NC}"
}

# Function to show usage
show_usage() {
    echo "Laravel Forge Rollback Script for HB837"
    echo ""
    echo "Usage: $0 --backup-path BACKUP_PATH [OPTIONS]"
    echo ""
    echo "Required:"
    echo "  --backup-path PATH     Path to backup directory on server"
    echo ""
    echo "Options:"
    echo "  --server SERVER        Forge server hostname (default: $FORGE_SERVER)"
    echo "  --path PATH            Project path on server (default: $PROJECT_PATH)"
    echo "  --user USER            SSH user (default: $FORGE_USER)"
    echo "  --force                Skip confirmation prompts"
    echo "  --dry-run              Show what would be done without executing"
    echo "  --help                 Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0 --backup-path /home/projecttracker/backups/deployment_2025-07-15_14-30-25"
    echo "  $0 --backup-path /home/projecttracker/backups/deployment_2025-07-15_14-30-25 --dry-run"
    echo "  $0 --backup-path /home/projecttracker/backups/deployment_2025-07-15_14-30-25 --force"
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --backup-path)
            BACKUP_PATH="$2"
            shift 2
            ;;
        --server)
            FORGE_SERVER="$2"
            shift 2
            ;;
        --path)
            PROJECT_PATH="$2"
            shift 2
            ;;
        --user)
            FORGE_USER="$2"
            shift 2
            ;;
        --force)
            FORCE=true
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --help)
            show_usage
            exit 0
            ;;
        *)
            print_error "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Check required arguments
if [[ -z "$BACKUP_PATH" ]]; then
    print_error "Backup path is required!"
    echo ""
    show_usage
    exit 1
fi

# Header
echo -e "${YELLOW}🔄 Laravel Forge Rollback Script - HB837 Training Server${NC}"
echo -e "${YELLOW}=================================================${NC}"

# Display rollback information
print_info "Rollback Information:"
echo "   Server: $FORGE_SERVER"
echo "   User: $FORGE_USER"
echo "   Project Path: $PROJECT_PATH"
echo "   Backup Path: $BACKUP_PATH"
echo "   Dry Run: $DRY_RUN"

# Safety confirmation unless Force is used
if [[ "$FORCE" != "true" && "$DRY_RUN" != "true" ]]; then
    echo ""
    print_warning "WARNING: This will restore from backup and overwrite current files!"
    read -p "   Continue with rollback? (y/N): " confirmation
    if [[ "$confirmation" != "y" && "$confirmation" != "Y" ]]; then
        print_error "Rollback cancelled by user"
        exit 1
    fi
fi

# Function to execute SSH commands
execute_ssh_command() {
    local command="$1"
    local description="$2"
    
    print_progress "$description..."
    
    if [[ "$DRY_RUN" == "true" ]]; then
        echo -e "      ${MAGENTA}[DRY RUN] Would execute: ssh $FORGE_USER@$FORGE_SERVER '$command'${NC}"
        return 0
    fi
    
    if ssh "$FORGE_USER@$FORGE_SERVER" "$command"; then
        echo -e "      ${GREEN}✅ $description completed${NC}"
        return 0
    else
        echo -e "      ${RED}❌ Error: $description failed${NC}"
        return 1
    fi
}

# Main rollback process
echo ""
print_info "Starting Rollback Process..."

# Step 1: Test SSH connection
echo ""
echo -e "${CYAN}1️⃣ Testing SSH Connection...${NC}"
if ! execute_ssh_command "echo 'Connection test successful'" "Testing SSH connection"; then
    print_error "SSH connection failed. Please check your SSH configuration."
    exit 1
fi

# Step 2: Verify backup exists
echo ""
echo -e "${CYAN}2️⃣ Verifying Backup...${NC}"
if ! execute_ssh_command "test -d $BACKUP_PATH" "Checking if backup directory exists"; then
    print_error "Backup directory not found: $BACKUP_PATH"
    echo ""
    print_info "Available backups:"
    ssh "$FORGE_USER@$FORGE_SERVER" "ls -la /home/$FORGE_USER/backups/ 2>/dev/null || echo 'No backups directory found'"
    exit 1
fi

# List backup contents
execute_ssh_command "ls -la $BACKUP_PATH" "Listing backup contents"

# Step 3: Remove current folders
echo ""
echo -e "${CYAN}3️⃣ Removing Current Folders...${NC}"
folders_to_restore=("app" "config" "database" "resources" "routes")
for folder in "${folders_to_restore[@]}"; do
    execute_ssh_command "rm -rf $PROJECT_PATH/$folder" "Removing current $folder"
done

# Step 4: Restore from backup
echo ""
echo -e "${CYAN}4️⃣ Restoring from Backup...${NC}"
for folder in "${folders_to_restore[@]}"; do
    execute_ssh_command "cp -r $BACKUP_PATH/$folder $PROJECT_PATH/ 2>/dev/null || echo 'Backup for $folder not found, skipping'" "Restoring $folder"
done

# Step 5: Run Laravel optimizations
echo ""
echo -e "${CYAN}5️⃣ Running Laravel Optimizations...${NC}"
cd_command="cd $PROJECT_PATH"

execute_ssh_command "$cd_command && composer dump-autoload --optimize" "Running composer dump-autoload"
execute_ssh_command "$cd_command && php artisan optimize:clear" "Running php artisan optimize:clear"

# Step 6: Final verification
echo ""
echo -e "${CYAN}6️⃣ Final Verification...${NC}"
execute_ssh_command "$cd_command && php artisan --version" "Verifying Laravel installation"

# Completion message
echo ""
echo -e "${GREEN}🎉 Rollback Completed Successfully!${NC}"
echo -e "${GREEN}=================================================${NC}"
echo "   Server: $FORGE_SERVER"
echo "   Restored from: $BACKUP_PATH"

if [[ "$DRY_RUN" != "true" ]]; then
    echo ""
    print_info "Next Steps:"
    echo "   1. Test the application: https://$FORGE_SERVER"
    echo "   2. Monitor logs for any issues"
    echo "   3. Consider investigating the original deployment issue"
fi

echo ""
print_status "Rollback script completed!"
