# Laravel Forge Rollback Script for HB837 Training Server
# Author: Generated by Task 7
# Date: July 15, 2025

param(
    [Parameter(Mandatory=$false)]
    [string]$ForgeServer = "projecttracker.hb837training.com",
    
    [Parameter(Mandatory=$false)]
    [string]$ProjectPath = "/home/projecttracker/projecttracker.hb837training.com",
    
    [Parameter(Mandatory=$false)]
    [string]$ForgeUser = "projecttracker",
    
    [Parameter(Mandatory=$true)]
    [string]$BackupPath,
    
    [switch]$Force,
    [switch]$DryRun
)

Write-Host "🔄 Laravel Forge Rollback Script - HB837 Training Server" -ForegroundColor Yellow
Write-Host "=================================================" -ForegroundColor Yellow

# Display rollback information
Write-Host "`n📊 Rollback Information:" -ForegroundColor Cyan
Write-Host "   Server: $ForgeServer" -ForegroundColor White
Write-Host "   User: $ForgeUser" -ForegroundColor White
Write-Host "   Project Path: $ProjectPath" -ForegroundColor White
Write-Host "   Backup Path: $BackupPath" -ForegroundColor White
Write-Host "   Dry Run: $DryRun" -ForegroundColor White

# Safety confirmation unless Force is used
if (-not $Force -and -not $DryRun) {
    Write-Host "`n⚠️  WARNING: This will restore from backup and overwrite current files!" -ForegroundColor Red
    $confirmation = Read-Host "   Continue with rollback? (y/N)"
    if ($confirmation -ne 'y' -and $confirmation -ne 'Y') {
        Write-Host "❌ Rollback cancelled by user" -ForegroundColor Red
        exit 1
    }
}

# Function to execute SSH commands
function Invoke-SSHCommand {
    param([string]$Command, [string]$Description)
    
    Write-Host "   🔄 $Description..." -ForegroundColor Yellow
    
    if ($DryRun) {
        Write-Host "      [DRY RUN] Would execute: ssh $ForgeUser@$ForgeServer '$Command'" -ForegroundColor Magenta
        return $true
    }
    
    try {
        $sshCommand = "ssh $ForgeUser@$ForgeServer `"$Command`""
        Invoke-Expression $sshCommand | Out-Null
        Write-Host "      ✅ $Description completed" -ForegroundColor Green
        return $true
    }
    catch {
        Write-Host "      ❌ Error: $($_.Exception.Message)" -ForegroundColor Red
        return $false
    }
}

# Main rollback process
Write-Host "`n🔧 Starting Rollback Process..." -ForegroundColor Cyan

# Step 1: Test SSH connection
Write-Host "`n1️⃣ Testing SSH Connection..." -ForegroundColor Cyan
if (-not (Invoke-SSHCommand "echo 'Connection test successful'" "Testing SSH connection")) {
    Write-Host "❌ SSH connection failed. Please check your SSH configuration." -ForegroundColor Red
    exit 1
}

# Step 2: Verify backup exists
Write-Host "`n2️⃣ Verifying Backup..." -ForegroundColor Cyan
if (-not (Invoke-SSHCommand "test -d $BackupPath" "Checking if backup directory exists")) {
    Write-Host "❌ Backup directory not found: $BackupPath" -ForegroundColor Red
    exit 1
}

# Step 3: Remove current folders
Write-Host "`n3️⃣ Removing Current Folders..." -ForegroundColor Cyan
$foldersToRestore = @("app", "config", "database", "resources", "routes")
foreach ($folder in $foldersToRestore) {
    Invoke-SSHCommand "rm -rf $ProjectPath/$folder" "Removing current $folder"
}

# Step 4: Restore from backup
Write-Host "`n4️⃣ Restoring from Backup..." -ForegroundColor Cyan
foreach ($folder in $foldersToRestore) {
    $restoreCommand = "if [ -d '$BackupPath/$folder' ]; then cp -r '$BackupPath/$folder' '$ProjectPath/'; else echo 'Backup for $folder not found, skipping'; fi"
    Invoke-SSHCommand $restoreCommand "Restoring $folder"
}

# Step 5: Run Laravel optimizations
Write-Host "`n5️⃣ Running Laravel Optimizations..." -ForegroundColor Cyan
$cdCommand = "cd $ProjectPath"

Invoke-SSHCommand "$cdCommand && composer dump-autoload --optimize" "Running composer dump-autoload"
Invoke-SSHCommand "$cdCommand && php artisan optimize:clear" "Running php artisan optimize:clear"

# Step 6: Final verification
Write-Host "`n6️⃣ Final Verification..." -ForegroundColor Cyan
Invoke-SSHCommand "$cdCommand && php artisan --version" "Verifying Laravel installation"

# Completion message
Write-Host "`n🎉 Rollback Completed Successfully!" -ForegroundColor Green
Write-Host "=================================================" -ForegroundColor Green
Write-Host "   Server: $ForgeServer" -ForegroundColor White
Write-Host "   Restored from: $BackupPath" -ForegroundColor White

if (-not $DryRun) {
    Write-Host "`n📋 Next Steps:" -ForegroundColor Cyan
    Write-Host "   1. Test the application: https://$ForgeServer" -ForegroundColor White
    Write-Host "   2. Monitor logs for any issues" -ForegroundColor White
    Write-Host "   3. Consider investigating the original deployment issue" -ForegroundColor White
}

Write-Host "`n✅ Rollback script completed!" -ForegroundColor Green
